### PR TITLE
Add miltiple lists and navigate for them

### PR DESCRIPTION
**Pull request by vovkanaz**
I have a great fuckup, and now does not understand anything! I am create a  method, for add new lists to user,:
  def create
      @list = current_user.lists.create( user: current_user, title: params[:list][:title])
      if @list.save
        redirect_to root_url, notice: 'List successfully created'
      else
        render 'new'
      end

but when action create is run. I have got an error:

I understand, that current_list expect params_id in url, and it's exists.

### CODE REVIEW

**Comment by kotsolesya** [comment]
the same

**Comment by Sheff3rd** [comment]
Пропиши localhost:3000/logout в адресной строке
Когда я склонировал твою программу, там была открыта сессия, но пользователя с id этой сессии не было. Как только я вышел из сессии, и зарегестрировался/зашел заново все заработало
Надеюсь помог ;)
****
image

**Comment by Sheff3rd** [comment]
Somehow session weren't destroyed.
Was that your problem? Answer me if it helps ;)

**Comment by vovkanaz** [comment]
Yes? after clear session all looks like very good, I saw this to, but i think this does not solve the problem.

**Comment by vovkanaz** [comment]
tttttttttttttttt

**Pull request closed without merging**
